name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    DISCORDTOKEN: ${{ vars.FAKETOKEN }}
    CLIENTID: ${{ vars.FAKETOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [21.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - run: |
                  npm install
                  npm run build
                  npm start
