name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21
                  cache: "npm"
            - run: npm install

            - name: Build with esbuild
              run: npm run build

            - name: Create .env with secrets
              uses: SpicyPizza/create-envfile@v2.0.2
              with:
                  envkey_FAKETOKEN: ${{ variables.FAKETOKEN }}
                  file_name: .env

            - name: CAT
              run: cat .env

            - name: Run server
              run: npm start
