# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [21.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Setup node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm install
            - run: npm ci

            - name: Build with esbuild
              uses: actions/setup-node@v3
            - run: npm run build

            - name: Create .env with secrets
              uses: SpicyPizza/create-envfile@v2.0.2
              with:
                  envkey_DEBUG: false
                  envkey_CLIENTID: ${{ secrets.CLIENTID }}
                  envkey_DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
                  file_name: .env

            - name: Run server
              uses: actions/setup-node@v3
            - run: npm start
